### ISSUE TITLE
Issue with codes indented with tab-characters (v6.12.0)

### ISSUE THREAD

**Issue by alchn** [pmd/pmd-designer#14]
Having issue with xpath execution if source codes are indented with tab-characters.  

Steps to reproduce the behaviour:
1. Launch the designer from run.sh
2. Entered a sample class indented with tabs, AST generated fine.
3. Entered in XPathExpression, `//MethodDeclaration`
4. Matched Nodes panel shown 'No match in text'
5. Replaces all the tabs with space-chars, all method nodes were correctly found.

**Expected behaviour**
Indentation characters should not cause inconsistent behaviour in nodes detection.

 - OS: MacOS Mojave
 - Java: 
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

**Comment by oowekyala** [comment]
Thanks for the report, I'll investigate shortly

**Comment by oowekyala** [comment]
Hi, this will be fixed in the next release (#15)

I had noticed the bug but hadn't pinned it down on the presence of tabs in the input. So, thanks :)
