### ISSUE TITLE
Rule export escapes special characters in rules unnecessarily

### ISSUE THREAD

**Issue by aldaris** [pmd/pmd-designer#27]
**Describe the bug**
When trying to export the following rule:

```
//PrimaryPrefix/Name[@Image[ends-with(., 'Instant.now')]][pmd-java:typeIs('java.time.Instant')]|
//PrimaryPrefix/Name[@Image='now'][//ImportDeclaration[@Static=true()]/Name[@Image='java.time.Instant.now' or @Image='java.time.Instant']]
```

The export result pane displays the rule incorrectly escaped:

```
         <value>
<![CDATA[
//PrimaryPrefix/Name[@Image[ends-with(., &apos;Instant.now&apos;)]][pmd-java:typeIs(&apos;java.time.Instant&apos;)]|
//PrimaryPrefix/Name[@Image=&apos;now&apos;][//ImportDeclaration[@Static=true()]/Name[@Image=&apos;java.time.Instant.now&apos; or @Image=&apos;java.time.Instant&apos;]]
]]>
         </value>
```

Within a CDATA it should not be necessary to escape apostrophe as `&apos;`, and the same seemed to happen with double quotes as well.

**To Reproduce**
1. Launch the designer from run.sh designer
1. Specify rule as above
2. Click on Export XPath to XML rule
3. Look at Export result pane
4. When you try to use the rule as is with pmd, the rule parser will blow up with an XPath parsing exception.

**Expected behavior**
The CDATA body is not escaped unnecessarily.

**Screenshots**
Let me know if you need one.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Java:
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

**Comment by oowekyala** [comment]
@aldaris Thanks for the report, indeed this is a bug
