### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by bpappin** [pmd/pmd-designer#32]
I only see support in the designer for a few languages, but PMD supports many more.
It would be good to be able to use any of the languages that are supported.

**Comment by adangel** [comment]
PMD consists actually of two tools:
* CPD (copy paste detector)
* and PMD itself

Language support for CPD is easier (only a tokenizer is needed). Therefore it supports many languages. Many more languages than PMD.
Language support for PMD is a bit harder (it requires a full parser). We support a couple of languages, but not as many as for CPD.

Here are the languages supported for PMD:
* https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#supported-languages (with the links to the available rules)

Here are the languages supported for CPD:
* https://pmd.github.io/latest/pmd_userdocs_cpd.html#supported-languages

So, I believe, the pmd-designer supports all languages, that PMD supports.
Is there a specific language you are missing?

**Comment by oowekyala** [comment]
I think we can close this. The designer is meant only for PMD-supported languages, and not useful for CPD languages.
