### ISSUE TITLE
Wrong qualified name?

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [pmd/pmd-designer#60]
**Describe the bug**
The designer tool is nice but i think it might show the wrong class

**To Reproduce**
1. 
```
export JAVAFX_HOME=/Users/nbaumgartner/Library/Java/JavaVirtualMachines/javafx-sdk-17.0.7 pmd-bin-6.55.0/bin/run.sh designer
```
3.
```

package com.example;

import javafx.scene.control.Button;

public class Test {
    private String foo;

    class Button{

    }

    public Button button;
}
```

**Expected behavior**
Altough there is a import for Button in the class we define an own class Button. The expected qualified name should be: "com.example.Text.Button" and not "javafx.scene.control.Button"

**Screenshots**
<img width="2032" alt="Bildschirmfoto 2023-05-14 um 18 27 59" src="https://github.com/pmd/pmd-designer/assets/33295329/3b2cd321-d999-407e-973e-f6b2d188f6a5">

 
**Additional context**
<img width="516" alt="Bildschirmfoto 2023-05-14 um 18 28 58" src="https://github.com/pmd/pmd-designer/assets/33295329/53779916-f17b-4a91-9585-c92094f7386f">

**Comment by jsotuyod** [comment]
@NilsBaumgartner1994 thanks for the report. This is actually an issue on PMD itself and not the designer, and should be fixed in PMD 7 where shadowing has been properly and fully implemented. If you are still facing an issue with PMD 7.0.0-rc2 feel free to open a new issue.
